# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3f0748011c90c9ffd24992604c87acb2c26e22bc7edf46b2028ca4d1a3c4fd514ddfa1f07290677249f02f57588538fc91148eca3bb70930fbbe973b52ea30f

test:
  secret_key_base: 22ef53745bcb527defadccaabef89a2b19184fa7d5b1349631c110cfcefad0ceaeffb2a07187c9a76bfa2ea39348a44a8e498ea3ff36f10781436d9f2dd590b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
